/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.com.tropisol.vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.com.tropisol.control.CtrlReporteSemanal;
import mx.com.tropisol.modelo.ReporteSemanal;

/**
 *
 * @author Rodrigo
 */
public class FrmVistaReporteSemanalDeCalidad extends javax.swing.JFrame {
DefaultTableModel reportesemana;    
    String datosreportesemana[][]={};
    String tituloTablaReportesemana[]={"SEMANA #","PERIODO","FECHA DE RECEPCION DE MATERIAL","# FOLIO INSP","DESCRIPCION DE MATERIAL",
        "MEDIDA/COLOR/TAMAÑO","PROVEEDOR","FACTURA/FOLIO","CANTIDAD RECIBIDA","CANTIDAD INSPECCIONADA","%","PROBLEMA",
        "RESULTADO APROVADO Y/O RECHAZADO","RESUMEN DE AUDITORIA","OBSERVACIONES"};

   
    /**
     * Creates new form FrmVistaAccesorios
     */
    public FrmVistaReporteSemanalDeCalidad() {
        initComponents();
           reportesemana = new DefaultTableModel(datosreportesemana, tituloTablaReportesemana);
        tblReporteSemanal.setModel(reportesemana);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnlFondoLogo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNoSemana = new javax.swing.JTextField();
        txtPeriodo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFolioInsp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResumenAuditorio = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tztmedidacolortamaño = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFacturafolio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbProveedor = new javax.swing.JComboBox<String>();
        jLabel12 = new javax.swing.JLabel();
        txtCantidadrecibida = new javax.swing.JTextField();
        txtCantidadInspeccionada = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtressultados = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDesMaterial = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtProblemas = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tztObservaciones = new javax.swing.JTextArea();
        btnAgregar = new javax.swing.JButton();
        btnguardad = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblReporteSemanal = new javax.swing.JTable();
        btneditarfila = new javax.swing.JButton();
        dateFecharecepci = new com.toedter.calendar.JDateChooser();
        lblFondo3 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        lblFondo2 = new javax.swing.JLabel();
        lblFondo5 = new javax.swing.JLabel();
        lblFondo1 = new javax.swing.JLabel();
        lblFondo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reporte Semanal De Calidad De Almacen");

        pnlFondo.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(251, 182, 136));

        pnlFondoLogo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel2.setText("REPORTE DE CALIDAD SEMANAL");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/logotropisol.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlFondoLogoLayout = new javax.swing.GroupLayout(pnlFondoLogo);
        pnlFondoLogo.setLayout(pnlFondoLogoLayout);
        pnlFondoLogoLayout.setHorizontalGroup(
            pnlFondoLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addContainerGap())
        );
        pnlFondoLogoLayout.setVerticalGroup(
            pnlFondoLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel1.setText("Semana #:");

        txtNoSemana.setName(""); // NOI18N

        txtPeriodo.setName(""); // NOI18N

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel3.setText("Periodo:");

        txtFolioInsp.setName(""); // NOI18N

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel4.setText("# Folio Insp.:");

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel5.setText("Fecha de recepción de material:");

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel6.setText("Descripción del");

        txtResumenAuditorio.setColumns(20);
        txtResumenAuditorio.setRows(5);
        jScrollPane1.setViewportView(txtResumenAuditorio);

        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel7.setText("Medida/Color/");

        tztmedidacolortamaño.setColumns(20);
        tztmedidacolortamaño.setRows(5);
        jScrollPane2.setViewportView(tztmedidacolortamaño);

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel8.setText("material:");

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel9.setText("Tamaño:");

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel10.setText("Factura folio:");

        txtFacturafolio.setName(""); // NOI18N

        jLabel11.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel11.setText("Proveedor:");

        cmbProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "CASA DIAZ", "KINGTEXT" }));

        jLabel12.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel12.setText("Cantidad recibida:");

        txtCantidadrecibida.setName(""); // NOI18N

        txtCantidadInspeccionada.setName(""); // NOI18N

        jLabel13.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel13.setText("Cantidad inspeccionada:");

        jLabel14.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel14.setText("Porcentaje (%):");

        txtPorcentaje.setName(""); // NOI18N

        jLabel16.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel16.setText("Problema:");

        txtressultados.setName(""); // NOI18N

        jLabel17.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel17.setText("Resultados");

        txtDesMaterial.setColumns(20);
        txtDesMaterial.setRows(5);
        jScrollPane3.setViewportView(txtDesMaterial);

        jLabel18.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel18.setText("Aprobado y/o");

        jLabel19.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel19.setText("Rechazado:");

        txtProblemas.setColumns(20);
        txtProblemas.setRows(5);
        jScrollPane4.setViewportView(txtProblemas);

        jLabel20.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel20.setText("Resumen de");

        jLabel21.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel21.setText("auditoria:");

        jLabel22.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel22.setText("Observaciones:");

        tztObservaciones.setColumns(20);
        tztObservaciones.setRows(5);
        jScrollPane5.setViewportView(tztObservaciones);

        btnAgregar.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnguardad.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        btnguardad.setText("Guardar reporte");
        btnguardad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardadActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        jButton4.setText("Ver reportes por semana");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tblReporteSemanal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tblReporteSemanal);

        btneditarfila.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        btneditarfila.setText("Corregir y/o editar fila");
        btneditarfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarfilaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondoLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNoSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPeriodo))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dateFecharecepci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel22))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                            .addComponent(jScrollPane3))))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFolioInsp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFacturafolio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtressultados, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCantidadrecibida, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCantidadInspeccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(317, 317, 317)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(122, 122, 122)
                                        .addComponent(btneditarfila, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(337, 337, 337)
                        .addComponent(btnguardad, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlFondoLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNoSemana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPeriodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFolioInsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFacturafolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel19)
                        .addComponent(txtressultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCantidadrecibida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(txtCantidadInspeccionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel14)
                        .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateFecharecepci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btneditarfila)
                    .addComponent(btnAgregar))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(btnguardad))
                .addContainerGap())
        );

        pnlFondo.add(jPanel1);
        jPanel1.setBounds(20, 20, 1220, 470);

        lblFondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/fondo1.jpg"))); // NOI18N
        pnlFondo.add(lblFondo3);
        lblFondo3.setBounds(-140, 80, 520, 430);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/fondo1.jpg"))); // NOI18N
        pnlFondo.add(lblFondo);
        lblFondo.setBounds(520, 80, 750, 430);

        lblFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/fondo1.jpg"))); // NOI18N
        pnlFondo.add(lblFondo2);
        lblFondo2.setBounds(490, 0, 780, 80);

        lblFondo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/fondo1.jpg"))); // NOI18N
        pnlFondo.add(lblFondo5);
        lblFondo5.setBounds(-140, 0, 480, 80);

        lblFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/fondo1.jpg"))); // NOI18N
        pnlFondo.add(lblFondo1);
        lblFondo1.setBounds(370, 80, 750, 430);

        lblFondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/fondo1.jpg"))); // NOI18N
        pnlFondo.add(lblFondo4);
        lblFondo4.setBounds(340, 0, 780, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1264, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1280, 544));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
      List<ReporteSemanal> reportsWeek = new ArrayList<>();
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
      ReporteSemanal reporte= new ReporteSemanal();
      reporte.setCantidadinspeccionada(txtCantidadInspeccionada.getText());
      reporte.setCantidadrecibida(txtCantidadrecibida.getText());
      reporte.setDescripcionmaterial(txtDesMaterial.getText().toUpperCase());
      reporte.setFacturafolio(txtFacturafolio.getText());
      reporte.setFecharecepcion(dateFecharecepci.getDateFormatString());
      reporte.setFolioinsp(txtFolioInsp.getText());
      reporte.setMedidacolortamaño(tztmedidacolortamaño.getText().toUpperCase());
      reporte.setObservaciones(tztObservaciones.getText().toUpperCase());
      reporte.setPeriodo(txtPeriodo.getText().toUpperCase());
      reporte.setPorcentaje(txtPorcentaje.getText());
      reporte.setProblema(txtProblemas.getText().toUpperCase());
      reporte.setProveedor(cmbProveedor.getSelectedItem().toString().toUpperCase());
      reporte.setResultadoaprobadorechazado(txtressultados.getText().toUpperCase());
      reporte.setResumenauditoria(txtResumenAuditorio.getText().toUpperCase());
      reporte.setSemana(txtNoSemana.getText());
     
        CtrlReporteSemanal ctrl= new CtrlReporteSemanal();
        ctrl.AgregarReporteSemanal(reporte);
       reportsWeek= ctrl.ConsultarPorSemana(txtNoSemana.getText());
       
        while (reportesemana.getRowCount() > 0) {
            reportesemana.removeRow(0);
        }

      
        for (int i = 0; i < reportsWeek.size(); i++) {
      String SEMANA = reportsWeek.get(i).getSemana();
      String PERIODO= reportsWeek.get(i).getPeriodo();
      String FECHA= reportsWeek.get(i).getFecharecepcion();
      String FOLIOINSP= reportsWeek.get(i).getFolioinsp();
      String DESCRIPCION= reportsWeek.get(i).getDescripcionmaterial();
      String MCT= reportsWeek.get(i).getMedidacolortamaño();
      String PROVEEDOR= reportsWeek.get(i).getProveedor();
      String FACTURAFOLIO= reportsWeek.get(i).getFacturafolio();
      String RECIBIDA= reportsWeek.get(i).getCantidadrecibida();
      String INSPECCIONADA= reportsWeek.get(i).getCantidadinspeccionada();        
      String PORCENTAJE= reportsWeek.get(i).getPorcentaje();
      String PROBLEMA= reportsWeek.get(i).getProblema();
      String RESULTADO= reportsWeek.get(i).getResultadoaprobadorechazado();
      String RESUMEN= reportsWeek.get(i).getResumenauditoria();
      String OBSERVACIONES= reportsWeek.get(i).getObservaciones();     
      String datos[]={SEMANA,PERIODO,FECHA,FOLIOINSP,DESCRIPCION,MCT,PROVEEDOR,FACTURAFOLIO,RECIBIDA,INSPECCIONADA,PORCENTAJE,PROBLEMA,
        RESULTADO,RESUMEN,OBSERVACIONES};
      reportesemana.addRow(datos);   
        }
          
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnguardadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardadActionPerformed
       
        CtrlReporteSemanal ctrl= new CtrlReporteSemanal();
    
       reportsWeek= ctrl.ConsultarPorSemana(txtNoSemana.getText());
        if(reportsWeek.isEmpty()){
        JOptionPane.showMessageDialog(null, "No Se Guardo Correctamente El Reporte");  
        } else{
                    JOptionPane.showMessageDialog(null, "Se Guardo Correctamente El Reporte");  
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnguardadActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        FrmVistaTodosLosReportesPorSemana frm= new FrmVistaTodosLosReportesPorSemana();
frm.setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btneditarfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarfilaActionPerformed
        int seleccion =this.tblReporteSemanal.getSelectedRow();
        ReporteSemanal reporte= new ReporteSemanal();
        CtrlReporteSemanal ctrl= new CtrlReporteSemanal();
        reporte=this.reportsWeek.get(seleccion);
        reporte.setCantidadinspeccionada(this.tblReporteSemanal.getValueAt(seleccion, 9).toString());
        reporte.setCantidadrecibida(this.tblReporteSemanal.getValueAt(seleccion, 8).toString());
        reporte.setDescripcionmaterial(this.tblReporteSemanal.getValueAt(seleccion, 4).toString().toUpperCase());
        reporte.setFacturafolio(this.tblReporteSemanal.getValueAt(seleccion, 7).toString());
        reporte.setFecharecepcion(this.tblReporteSemanal.getValueAt(seleccion, 2).toString());
        reporte.setFolioinsp(this.tblReporteSemanal.getValueAt(seleccion, 3).toString());
        reporte.setMedidacolortamaño(this.tblReporteSemanal.getValueAt(seleccion, 5).toString().toUpperCase());
        reporte.setObservaciones(this.tblReporteSemanal.getValueAt(seleccion, 14).toString().toUpperCase());
        reporte.setPeriodo(this.tblReporteSemanal.getValueAt(seleccion, 1).toString().toUpperCase());
        reporte.setPorcentaje(this.tblReporteSemanal.getValueAt(seleccion, 10).toString());
        reporte.setProblema(this.tblReporteSemanal.getValueAt(seleccion, 11).toString().toUpperCase());
        reporte.setProveedor(this.tblReporteSemanal.getValueAt(seleccion, 6).toString().toUpperCase());
        reporte.setResultadoaprobadorechazado(this.tblReporteSemanal.getValueAt(seleccion, 12).toString().toUpperCase());
        reporte.setResumenauditoria(this.tblReporteSemanal.getValueAt(seleccion, 13).toString().toUpperCase());
        reporte.setSemana(this.tblReporteSemanal.getValueAt(seleccion, 0).toString());

        ctrl.ModificarReporteSemanal(reporte);

        this.reportsWeek= ctrl.ConsultarPorSemana(txtNoSemana.getText());

        while (reportesemana.getRowCount() > 0) {
            reportesemana.removeRow(0);
        }

        for (int i = 0; i < this.reportsWeek.size(); i++) {
            String SEMANA = this.reportsWeek.get(i).getSemana();
            String PERIODO= this.reportsWeek.get(i).getPeriodo();
            String FECHA= this.reportsWeek.get(i).getFecharecepcion();
            String FOLIOINSP= this.reportsWeek.get(i).getFolioinsp();
            String DESCRIPCION= this.reportsWeek.get(i).getDescripcionmaterial();
            String MCT= this.reportsWeek.get(i).getMedidacolortamaño();
            String PROVEEDOR= this.reportsWeek.get(i).getProveedor();
            String FACTURAFOLIO= this.reportsWeek.get(i).getFacturafolio();
            String RECIBIDA= this.reportsWeek.get(i).getCantidadrecibida();
            String INSPECCIONADA= this.reportsWeek.get(i).getCantidadinspeccionada();
            String PORCENTAJE= this.reportsWeek.get(i).getPorcentaje();
            String PROBLEMA= this.reportsWeek.get(i).getProblema();
            String RESULTADO= this.reportsWeek.get(i).getResultadoaprobadorechazado();
            String RESUMEN= this.reportsWeek.get(i).getResumenauditoria();
            String OBSERVACIONES= this.reportsWeek.get(i).getObservaciones();
            String datos[]={SEMANA,PERIODO,FECHA,FOLIOINSP,DESCRIPCION,MCT,PROVEEDOR,FACTURAFOLIO,RECIBIDA,INSPECCIONADA,PORCENTAJE,PROBLEMA,
                RESULTADO,RESUMEN,OBSERVACIONES};
            reportesemana.addRow(datos);
        } // TODO add your handling code here:
    }//GEN-LAST:event_btneditarfilaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVistaReporteSemanalDeCalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVistaReporteSemanalDeCalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVistaReporteSemanalDeCalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVistaReporteSemanalDeCalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVistaReporteSemanalDeCalidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btneditarfila;
    private javax.swing.JButton btnguardad;
    private javax.swing.JComboBox<String> cmbProveedor;
    private com.toedter.calendar.JDateChooser dateFecharecepci;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFondo1;
    private javax.swing.JLabel lblFondo2;
    private javax.swing.JLabel lblFondo3;
    private javax.swing.JLabel lblFondo4;
    private javax.swing.JLabel lblFondo5;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlFondoLogo;
    private javax.swing.JTable tblReporteSemanal;
    private javax.swing.JTextField txtCantidadInspeccionada;
    private javax.swing.JTextField txtCantidadrecibida;
    private javax.swing.JTextArea txtDesMaterial;
    private javax.swing.JTextField txtFacturafolio;
    private javax.swing.JTextField txtFolioInsp;
    private javax.swing.JTextField txtNoSemana;
    private javax.swing.JTextField txtPeriodo;
    private javax.swing.JTextField txtPorcentaje;
    private javax.swing.JTextArea txtProblemas;
    private javax.swing.JTextArea txtResumenAuditorio;
    private javax.swing.JTextField txtressultados;
    private javax.swing.JTextArea tztObservaciones;
    private javax.swing.JTextArea tztmedidacolortamaño;
    // End of variables declaration//GEN-END:variables
}
