/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.com.tropisol.vistas;

/**
 *
 * @author Rodrigo
 */
public class FrmVistaAccesorios extends javax.swing.JFrame {

    /**
     * Creates new form FrmVistaAccesorios
     */
    public FrmVistaAccesorios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnlFondoLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblFondo3 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        lblFondo2 = new javax.swing.JLabel();
        lblFondo5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(251, 182, 136));

        pnlFondoLogo.setBackground(new java.awt.Color(255, 255, 255));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/logotropisol.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlFondoLogoLayout = new javax.swing.GroupLayout(pnlFondoLogo);
        pnlFondoLogo.setLayout(pnlFondoLogoLayout);
        pnlFondoLogoLayout.setHorizontalGroup(
            pnlFondoLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLogoLayout.createSequentialGroup()
                .addGap(0, 680, Short.MAX_VALUE)
                .addComponent(lblLogo))
        );
        pnlFondoLogoLayout.setVerticalGroup(
            pnlFondoLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLogoLayout.createSequentialGroup()
                .addComponent(lblLogo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondoLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlFondoLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 433, Short.MAX_VALUE))
        );

        pnlFondo.add(jPanel1);
        jPanel1.setBounds(20, 20, 780, 470);

        lblFondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/fondo1.jpg"))); // NOI18N
        pnlFondo.add(lblFondo3);
        lblFondo3.setBounds(-140, 80, 520, 430);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/fondo1.jpg"))); // NOI18N
        pnlFondo.add(lblFondo);
        lblFondo.setBounds(330, 80, 500, 430);

        lblFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/fondo1.jpg"))); // NOI18N
        pnlFondo.add(lblFondo2);
        lblFondo2.setBounds(330, 0, 510, 80);

        lblFondo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/fondo1.jpg"))); // NOI18N
        pnlFondo.add(lblFondo5);
        lblFondo5.setBounds(-140, 0, 480, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(841, 544));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVistaAccesorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVistaAccesorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVistaAccesorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVistaAccesorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVistaAccesorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFondo2;
    private javax.swing.JLabel lblFondo3;
    private javax.swing.JLabel lblFondo5;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlFondoLogo;
    // End of variables declaration//GEN-END:variables
}
