/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.com.tropisol.vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.com.tropisol.control.CtrlReporteSemanal;
import mx.com.tropisol.modelo.ReporteSemanal;

/**
 *
 * @author Rodrigo
 */
public class FrmVistaTodosLosReportesPorSemana extends javax.swing.JFrame {
DefaultTableModel reportesemana;    
    String datosreportesemana[][]={};
    String tituloTablaReportesemana[]={"SEMANA #","PERIODO","FECHA DE RECEPCION DE MATERIAL","# FOLIO INSP","DESCRIPCION DE MATERIAL",
        "MEDIDA/COLOR/TAMAÑO","PROVEEDOR","FACTURA/FOLIO","CANTIDAD RECIBIDA","CANTIDAD INSPECCIONADA","%","PROBLEMA",
        "RESULTADO APROVADO Y/O RECHAZADO","RESUMEN DE AUDITORIA","OBSERVACIONES"};

    /**
     * Creates new form FrmVistaTodosLosReportesPorSemana
     */
    public FrmVistaTodosLosReportesPorSemana() {
        initComponents();
        reportesemana = new DefaultTableModel(datosreportesemana, tituloTablaReportesemana);
        tblReporteSemanal.setModel(reportesemana);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        pnlFondoLogo7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblLogo7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNoSemana = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblReporteSemanal = new javax.swing.JTable();
        btnEliminarfila = new javax.swing.JButton();
        btneditarfila = new javax.swing.JButton();
        btnguardarPdf = new javax.swing.JButton();
        lblFondo3 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        lblFondo2 = new javax.swing.JLabel();
        lblFondo5 = new javax.swing.JLabel();
        lblFondo1 = new javax.swing.JLabel();
        lblFondo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VER LOS REPORTES DE CALIDAD POR SEMANA");

        pnlFondo7.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(251, 182, 136));

        pnlFondoLogo7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel9.setText("REPORTE DE CALIDAD SEMANAL");

        lblLogo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/logotropisol.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlFondoLogo7Layout = new javax.swing.GroupLayout(pnlFondoLogo7);
        pnlFondoLogo7.setLayout(pnlFondoLogo7Layout);
        pnlFondoLogo7Layout.setHorizontalGroup(
            pnlFondoLogo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLogo7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo7)
                .addContainerGap())
        );
        pnlFondoLogo7Layout.setVerticalGroup(
            pnlFondoLogo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLogo7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
            .addComponent(lblLogo7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel1.setText("Semana #:");

        txtNoSemana.setName(""); // NOI18N

        btnAgregar.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        btnAgregar.setText("Buscar Reportes");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tblReporteSemanal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tblReporteSemanal);

        btnEliminarfila.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        btnEliminarfila.setText("Eliminar la fila seleccionada");
        btnEliminarfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarfilaActionPerformed(evt);
            }
        });

        btneditarfila.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        btneditarfila.setText("Corregir y/o editar fila");
        btneditarfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarfilaActionPerformed(evt);
            }
        });

        btnguardarPdf.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        btnguardarPdf.setText("Guardar en PDF");
        btnguardarPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarPdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondoLogo7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNoSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnEliminarfila, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btneditarfila, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnguardarPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(pnlFondoLogo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNoSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregar)
                        .addComponent(btnEliminarfila)
                        .addComponent(btneditarfila)
                        .addComponent(btnguardarPdf)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pnlFondo7.add(jPanel8);
        jPanel8.setBounds(20, 20, 1220, 470);

        lblFondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/fondo1.jpg"))); // NOI18N
        pnlFondo7.add(lblFondo3);
        lblFondo3.setBounds(-140, 80, 520, 430);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/fondo1.jpg"))); // NOI18N
        pnlFondo7.add(lblFondo);
        lblFondo.setBounds(520, 80, 750, 430);

        lblFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/fondo1.jpg"))); // NOI18N
        pnlFondo7.add(lblFondo2);
        lblFondo2.setBounds(490, 0, 780, 80);

        lblFondo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/fondo1.jpg"))); // NOI18N
        pnlFondo7.add(lblFondo5);
        lblFondo5.setBounds(-140, 0, 480, 80);

        lblFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/fondo1.jpg"))); // NOI18N
        pnlFondo7.add(lblFondo1);
        lblFondo1.setBounds(370, 80, 750, 430);

        lblFondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/com/tropisol/imagenes/fondo1.jpg"))); // NOI18N
        pnlFondo7.add(lblFondo4);
        lblFondo4.setBounds(340, 0, 780, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo7, javax.swing.GroupLayout.PREFERRED_SIZE, 1269, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFondo7, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1285, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 List<ReporteSemanal> reportsWeek = new ArrayList<>();
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    
        CtrlReporteSemanal ctrl= new CtrlReporteSemanal();
       
        this.reportsWeek= ctrl.ConsultarPorSemana(txtNoSemana.getText());
            
        while (reportesemana.getRowCount() > 0) {
            reportesemana.removeRow(0);
        }
        
        if(this.reportsWeek.isEmpty()){
            JOptionPane.showMessageDialog(null, "No Se Encuentran Registros De Esa Semana");
        }
        

        for (int i = 0; i < reportsWeek.size(); i++) {
            String SEMANA = reportsWeek.get(i).getSemana();
            String PERIODO= reportsWeek.get(i).getPeriodo();
            String FECHA= reportsWeek.get(i).getFecharecepcion();
            String FOLIOINSP= reportsWeek.get(i).getFolioinsp();
            String DESCRIPCION= reportsWeek.get(i).getDescripcionmaterial();
            String MCT= reportsWeek.get(i).getMedidacolortamaño();
            String PROVEEDOR= reportsWeek.get(i).getProveedor();
            String FACTURAFOLIO= reportsWeek.get(i).getFacturafolio();
            String RECIBIDA= reportsWeek.get(i).getCantidadrecibida();
            String INSPECCIONADA= reportsWeek.get(i).getCantidadinspeccionada();
            String PORCENTAJE= reportsWeek.get(i).getPorcentaje();
            String PROBLEMA= reportsWeek.get(i).getProblema();
            String RESULTADO= reportsWeek.get(i).getResultadoaprobadorechazado();
            String RESUMEN= reportsWeek.get(i).getResumenauditoria();
            String OBSERVACIONES= reportsWeek.get(i).getObservaciones();
            String datos[]={SEMANA,PERIODO,FECHA,FOLIOINSP,DESCRIPCION,MCT,PROVEEDOR,FACTURAFOLIO,RECIBIDA,INSPECCIONADA,PORCENTAJE,PROBLEMA,
                RESULTADO,RESUMEN,OBSERVACIONES};
            reportesemana.addRow(datos);
        }
    
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FrmVistaReporteSemanalDeCalidad frm= new FrmVistaReporteSemanalDeCalidad();
        frm.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnEliminarfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarfilaActionPerformed
        int seleccion =this.tblReporteSemanal.getSelectedRow();
        ReporteSemanal report= new ReporteSemanal();
        report=this.reportsWeek.get(seleccion);
        CtrlReporteSemanal ctrl= new CtrlReporteSemanal();
        ctrl.EliminarReporteSemanal(report.getIdReportesemnal());
        
            this.reportsWeek= ctrl.ConsultarPorSemana(txtNoSemana.getText());
  
        while (reportesemana.getRowCount() > 0) {
            reportesemana.removeRow(0);
        }

        for (int i = 0; i < reportsWeek.size(); i++) {
            String SEMANA = reportsWeek.get(i).getSemana();
            String PERIODO= reportsWeek.get(i).getPeriodo();
            String FECHA= reportsWeek.get(i).getFecharecepcion();
            String FOLIOINSP= reportsWeek.get(i).getFolioinsp();
            String DESCRIPCION= reportsWeek.get(i).getDescripcionmaterial();
            String MCT= reportsWeek.get(i).getMedidacolortamaño();
            String PROVEEDOR= reportsWeek.get(i).getProveedor();
            String FACTURAFOLIO= reportsWeek.get(i).getFacturafolio();
            String RECIBIDA= reportsWeek.get(i).getCantidadrecibida();
            String INSPECCIONADA= reportsWeek.get(i).getCantidadinspeccionada();
            String PORCENTAJE= reportsWeek.get(i).getPorcentaje();
            String PROBLEMA= reportsWeek.get(i).getProblema();
            String RESULTADO= reportsWeek.get(i).getResultadoaprobadorechazado();
            String RESUMEN= reportsWeek.get(i).getResumenauditoria();
            String OBSERVACIONES= reportsWeek.get(i).getObservaciones();
            String datos[]={SEMANA,PERIODO,FECHA,FOLIOINSP,DESCRIPCION,MCT,PROVEEDOR,FACTURAFOLIO,RECIBIDA,INSPECCIONADA,PORCENTAJE,PROBLEMA,
                RESULTADO,RESUMEN,OBSERVACIONES};
            reportesemana.addRow(datos);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarfilaActionPerformed

    private void btneditarfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarfilaActionPerformed
         int seleccion =this.tblReporteSemanal.getSelectedRow();
        ReporteSemanal reporte= new ReporteSemanal();        
        CtrlReporteSemanal ctrl= new CtrlReporteSemanal();
        reporte=this.reportsWeek.get(seleccion);
      reporte.setCantidadinspeccionada(this.tblReporteSemanal.getValueAt(seleccion, 9).toString());
      reporte.setCantidadrecibida(this.tblReporteSemanal.getValueAt(seleccion, 8).toString());
      reporte.setDescripcionmaterial(this.tblReporteSemanal.getValueAt(seleccion, 4).toString().toUpperCase());
      reporte.setFacturafolio(this.tblReporteSemanal.getValueAt(seleccion, 7).toString());
      reporte.setFecharecepcion(this.tblReporteSemanal.getValueAt(seleccion, 2).toString());
      reporte.setFolioinsp(this.tblReporteSemanal.getValueAt(seleccion, 3).toString());
      reporte.setMedidacolortamaño(this.tblReporteSemanal.getValueAt(seleccion, 5).toString().toUpperCase());
      reporte.setObservaciones(this.tblReporteSemanal.getValueAt(seleccion, 14).toString().toUpperCase());
      reporte.setPeriodo(this.tblReporteSemanal.getValueAt(seleccion, 1).toString().toUpperCase());
      reporte.setPorcentaje(this.tblReporteSemanal.getValueAt(seleccion, 10).toString());
      reporte.setProblema(this.tblReporteSemanal.getValueAt(seleccion, 11).toString().toUpperCase());
      reporte.setProveedor(this.tblReporteSemanal.getValueAt(seleccion, 6).toString().toUpperCase());
      reporte.setResultadoaprobadorechazado(this.tblReporteSemanal.getValueAt(seleccion, 12).toString().toUpperCase());
      reporte.setResumenauditoria(this.tblReporteSemanal.getValueAt(seleccion, 13).toString().toUpperCase());
      reporte.setSemana(this.tblReporteSemanal.getValueAt(seleccion, 0).toString());
        
        
       ctrl.ModificarReporteSemanal(reporte);
          
       this.reportsWeek= ctrl.ConsultarPorSemana(txtNoSemana.getText());
  
        while (reportesemana.getRowCount() > 0) {
            reportesemana.removeRow(0);
        }

        for (int i = 0; i < this.reportsWeek.size(); i++) {
            String SEMANA = this.reportsWeek.get(i).getSemana();
            String PERIODO= this.reportsWeek.get(i).getPeriodo();
            String FECHA= this.reportsWeek.get(i).getFecharecepcion();
            String FOLIOINSP= this.reportsWeek.get(i).getFolioinsp();
            String DESCRIPCION= this.reportsWeek.get(i).getDescripcionmaterial();
            String MCT= this.reportsWeek.get(i).getMedidacolortamaño();
            String PROVEEDOR= this.reportsWeek.get(i).getProveedor();
            String FACTURAFOLIO= this.reportsWeek.get(i).getFacturafolio();
            String RECIBIDA= this.reportsWeek.get(i).getCantidadrecibida();
            String INSPECCIONADA= this.reportsWeek.get(i).getCantidadinspeccionada();
            String PORCENTAJE= this.reportsWeek.get(i).getPorcentaje();
            String PROBLEMA= this.reportsWeek.get(i).getProblema();
            String RESULTADO= this.reportsWeek.get(i).getResultadoaprobadorechazado();
            String RESUMEN= this.reportsWeek.get(i).getResumenauditoria();
            String OBSERVACIONES= this.reportsWeek.get(i).getObservaciones();
            String datos[]={SEMANA,PERIODO,FECHA,FOLIOINSP,DESCRIPCION,MCT,PROVEEDOR,FACTURAFOLIO,RECIBIDA,INSPECCIONADA,PORCENTAJE,PROBLEMA,
                RESULTADO,RESUMEN,OBSERVACIONES};
            reportesemana.addRow(datos);
        } // TODO add your handling code here:
    }//GEN-LAST:event_btneditarfilaActionPerformed

    private void btnguardarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarPdfActionPerformed

        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarPdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVistaTodosLosReportesPorSemana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVistaTodosLosReportesPorSemana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVistaTodosLosReportesPorSemana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVistaTodosLosReportesPorSemana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVistaTodosLosReportesPorSemana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminarfila;
    private javax.swing.JButton btneditarfila;
    private javax.swing.JButton btnguardarPdf;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFondo1;
    private javax.swing.JLabel lblFondo2;
    private javax.swing.JLabel lblFondo3;
    private javax.swing.JLabel lblFondo4;
    private javax.swing.JLabel lblFondo5;
    private javax.swing.JLabel lblLogo7;
    private javax.swing.JPanel pnlFondo7;
    private javax.swing.JPanel pnlFondoLogo7;
    private javax.swing.JTable tblReporteSemanal;
    private javax.swing.JTextField txtNoSemana;
    // End of variables declaration//GEN-END:variables
}
